

#!/data/data/com.termux/files/usr/bin/python

import requests
import json

def pull_requests(url):
    try:
        response = requests.get(url)
        response.raise_for_status()  # Raise an exception for HTTP errors
        data = response.json()
        return data
    except requests.exceptions.RequestException as err:
        print(f"Request Exception: {err}")
        return None
    except json.JSONDecodeError as err:
        print(f"JSON Decode Error: {err}")
        return None

def main():
    username = "your_username"
    repository = "your_repository"
    url = f"https://api.github.com/repos/{username}/{repository}/pulls"
    pulls = pull_requests(url)

    if pulls:
        for pull in pulls:
            print(f"Title: {pull['title']}")
            print(f"Number: {pull['number']}")
            print(f"State: {pull['state']}")
            print(f"URL: {pull['html_url']}")
            print("------------------------")

if __name__ == "__main__":
    main()
```
